name:  first-code
on:
  push: 
    branches:
     - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get first-code
        uses:  actions/checkout@v3
      - name: install packages
        run:  npm ci 
      - name: run npm lint
        run:  npm run lint
      - name: npm test run here
        run:  npm run test
    outputs:
      file-script: ${{ steps.publish.outputs.file-script }}

  build:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: get code 
        uses: actions/checkout@v3
      - name: run packages
        run: npm ci 
      - name: build web
        run: npm run build
      - name: public job output
        id:  publish
        run:  find diskfolder/*. -type f -execdir echo 'file-script={}' >> $GITHUB_OUTPUT ';'


      - uses: actions/upload-artifact@v4
        with:
            name: artifacts-upload
            path: diskfolder
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts 
        uses: actions/download-artifact@v4
        with:
            name: artifacts-upload
      - name: output artifacts     
        run:  ls

      - name: deploy code
        run: echo "deploying code........"


