name:  first-code
on:
  push: 
    branches:
     - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get first-code
        uses:  actions/checkout@v3
      - name: install packages
        run:  npm ci 
      - name: run npm lint
        run:  npm run lint
      - name: npm test run here
        run:  npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: get code 
        uses: actions/checkout@v3
      - name: run packages
        run: npm ci 
      - name: build web
        run: npm run build
      - uses: actions/upload-artifacts@v3 
        with:
            name: artifacts-upload
            path: |
             package.json
             index.html



  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy code
        run: echo "deploying code......."


